dist: xenial	
language: python
python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
before_install:
  - pip3 install -r requirements.txt
script:
  - python3 motifs.py -t ./data/template100.fa -q ./data/query10.fa
  - python3 motifs.py -t ./data/template100.fa -q ./data/degenerated10.fa
notifications:
  email: false
