dist: focal	
language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
cache: pip
install:
  - pip3 install -r requirements.txt
script:
  - python3 motifs.py -t ./data/template1000.fa -q ./data/query100.fa -p testrun
notifications:
  email: false
